version: '2'

services:
  app:
    build: subversion
    volumes:
      - /opt/docker/subversion/volumes/subversion/opt/svn:/opt/svn
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    environment:
      - REPOS=sample
