- hosts: all

  vars:
    service: subversion.service

  tasks:
    - name: set subversion systemd service
      template: src="{{ service }}.j2" dest="/etc/systemd/system/{{ service }}"
      notify: subversion restart

    - name: enable subversion systemd service
      service: name="{{ service }}" enabled=yes state=started daemon_reload=yes

  handlers:
    - name: subversion restart
      service: name=subversion state=restarted
